# This is a basic workflow to help you get started with Actions

name: AML Setup CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup and InstallDependencies
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8.5'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools pipenv
          pipenv install --dev

      # Runs flake8 and pytests
      - name: Run Tests
        run: |
        pipenv run flake8
        pipenv run pytest
